import * as React from "react";
import { useVirtualizer } from "@tanstack/react-virtual";
import { ChevronRight, Loader2, X } from "lucide-react";
import { SearchBox } from "~/components/SearchBox";
import type {
  CbsData,
  CbsLevelColor,
  CbsNode,
} from "~/config/cbs-sample-types";

/**
 * Web view of the formatted CBS sample workbooks. Two collapsible sections,
 * each a colour-by-depth collapsible hierarchy that mirrors its workbook's own
 * outline grouping. The (large) per-section data is generated by
 * scripts/build-cbs-sample.ts and lazy-loaded the first time a section opens, so
 * the page itself stays light.
 */

type ColorFn = (level: number) => CbsLevelColor;

// The workbooks colour L0 and L1 the same gold. Override L0 (the discipline
// roots) to a distinct red so the top of each hierarchy stands apart.
const L0_COLOR: CbsLevelColor = { fill: "#C0504D", text: "#FFFFFF" };
// Styling for an unknown/unmapped level.
const DEFAULT_LEVEL_COLOR: CbsLevelColor = { fill: "#ffffff", text: "#000000" };

function rowTypeBadge(rowType: string): { label: string; title: string } | null {
  if (rowType.includes("Sub")) return { label: "S", title: "Sub-code row" };
  if (rowType.includes("Material")) return { label: "M", title: "Material row" };
  return null;
}

/** Keep only nodes matching `needle` (lowercased name+code) plus their ancestors. */
function filterTree(
  nodes: CbsNode[],
  needle: string,
): { nodes: CbsNode[]; matches: number } {
  let matches = 0;
  const rec = (list: CbsNode[]): CbsNode[] => {
    const out: CbsNode[] = [];
    for (const n of list) {
      const selfMatch = n.haystack.includes(needle);
      const kids = rec(n.children);
      if (selfMatch || kids.length > 0) {
        if (selfMatch) matches++;
        out.push({ ...n, children: kids });
      }
    }
    return out;
  };
  return { nodes: rec(nodes), matches };
}

/**
 * One flattened tree row. Memoized and fed only primitives + stable refs
 * (`isOpen`/`isSelected` booleans, a stable `color`, stable callbacks) so that
 * scrolling the virtual list — and selecting/toggling — re-renders only the
 * rows whose own state changed, not the whole tree.
 */
const CbsRow = React.memo(function CbsRow({
  node,
  depth,
  hasChildren,
  isOpen,
  isSelected,
  onToggle,
  onSelect,
  color,
}: {
  node: CbsNode;
  depth: number;
  hasChildren: boolean;
  isOpen: boolean;
  isSelected: boolean;
  onToggle: (id: number) => void;
  onSelect: (node: CbsNode) => void;
  color: CbsLevelColor;
}) {
  const badge = rowTypeBadge(node.rowType);
  const uom = node.fields["UOM"];

  return (
    <div
      role="treeitem"
      aria-level={node.level + 1}
      aria-expanded={hasChildren ? isOpen : undefined}
      aria-selected={isSelected}
      onClick={() => onSelect(node)}
      style={{
        backgroundColor: color.fill,
        color: color.text,
        paddingLeft: 8 + depth * 18,
      }}
      className={`flex cursor-pointer items-center gap-2 border-b border-black/5 py-1 pr-3 text-sm transition-[filter] hover:brightness-95 ${
        isSelected ? "ring-2 ring-inset ring-sky-900/60" : ""
      }`}
    >
      {hasChildren ? (
        <button
          type="button"
          aria-label={isOpen ? "Collapse" : "Expand"}
          onClick={(e) => {
            e.stopPropagation();
            onToggle(node.id);
          }}
          className="grid size-4 shrink-0 place-items-center rounded hover:bg-black/10"
        >
          <ChevronRight
            size={13}
            className={`transition-transform ${isOpen ? "rotate-90" : ""}`}
          />
        </button>
      ) : (
        <span className="size-4 shrink-0 text-center opacity-40">·</span>
      )}
      <span className="shrink-0 font-mono text-xs tabular-nums opacity-80">
        {node.code}
      </span>
      <span className="truncate font-medium">{node.name}</span>
      {badge && (
        <span
          title={badge.title}
          className="shrink-0 rounded border border-current/30 px-1 text-[10px] leading-4 font-semibold opacity-70"
        >
          {badge.label}
        </span>
      )}
      {uom && (
        <span className="ml-auto shrink-0 font-mono text-[11px] opacity-70">
          {uom}
        </span>
      )}
    </div>
  );
});

/** A node paired with its depth — the flattened, currently-visible rows. */
type FlatRow = { node: CbsNode; depth: number };

/** Depth-first flatten of the nodes that are currently visible: a node's
 *  children are included only when it's expanded (or a search forces it open). */
function flattenVisible(
  nodes: CbsNode[],
  expanded: Set<number>,
  forceExpand: boolean,
): FlatRow[] {
  const out: FlatRow[] = [];
  const walk = (list: CbsNode[], depth: number) => {
    for (const n of list) {
      out.push({ node: n, depth });
      if (n.children.length > 0 && (forceExpand || expanded.has(n.id))) {
        walk(n.children, depth + 1);
      }
    }
  };
  walk(nodes, 0);
  return out;
}

function DetailPanel({
  node,
  detailColumns,
  color,
  onClose,
}: {
  node: CbsNode;
  detailColumns: string[];
  color: CbsLevelColor;
  onClose: () => void;
}) {
  return (
    <div className="flex h-full flex-col">
      <div
        className="flex items-start justify-between gap-2 rounded-t-lg px-4 py-3"
        style={{ backgroundColor: color.fill, color: color.text }}
      >
        <div className="min-w-0">
          <div className="font-mono text-xs tabular-nums opacity-80">
            {node.code}
          </div>
          <div className="text-sm font-semibold break-words">{node.name}</div>
          <div className="mt-0.5 text-[11px] opacity-70">
            Level {node.level} · {node.rowType}
          </div>
        </div>
        <button
          type="button"
          onClick={onClose}
          aria-label="Close details"
          className="shrink-0 rounded p-0.5 hover:bg-black/10"
        >
          <X size={15} />
        </button>
      </div>
      <dl className="min-h-0 flex-1 divide-y divide-slate-100 overflow-y-auto px-4 py-2 text-sm">
        {detailColumns
          .filter((col) => node.fields[col])
          .map((col) => (
            <div key={col} className="grid grid-cols-[9rem_1fr] gap-2 py-1.5">
              <dt className="text-xs font-medium text-slate-500">{col}</dt>
              <dd className="break-words text-slate-800">{node.fields[col]}</dd>
            </div>
          ))}
      </dl>
    </div>
  );
}

/** Row-count pills + the per-level colour legend. */
function CountsLegend({
  counts,
  levels,
  colorFor,
}: {
  counts: CbsData["meta"]["counts"];
  levels: number[];
  colorFor: ColorFn;
}) {
  return (
    <div className="mb-3 flex flex-wrap items-center gap-2">
      <span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-700">
        {counts.total.toLocaleString()} rows
      </span>
      <span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-600">
        {counts.original.toLocaleString()} original · {counts.subRows} sub ·{" "}
        {counts.materialRows} material
      </span>
      <span className="ml-1 flex flex-wrap items-center gap-1">
        {levels.map((lvl) => {
          const c = colorFor(lvl);
          return (
            <span
              key={lvl}
              title={`Level ${lvl}`}
              className="rounded px-1.5 py-0.5 text-[10px] font-semibold"
              style={{
                backgroundColor: c.fill,
                color: c.text,
                outline: "1px solid rgba(0,0,0,0.1)",
              }}
            >
              L{lvl}
            </span>
          );
        })}
      </span>
    </div>
  );
}

/** Search box + expand/collapse-all + (while searching) a match count. */
function HierarchyToolbar({
  query,
  setQuery,
  onExpandAll,
  onCollapseAll,
  matchCount,
}: {
  query: string;
  setQuery: (v: string) => void;
  onExpandAll: () => void;
  onCollapseAll: () => void;
  matchCount: number | null;
}) {
  return (
    <div className="mb-3 flex flex-wrap items-center gap-2">
      <SearchBox
        value={query}
        onChange={setQuery}
        placeholder="Search code or name…"
        ariaLabel="Search this CBS hierarchy"
        className="h-8 w-64"
      />
      <button
        type="button"
        onClick={onExpandAll}
        className="rounded-md border border-slate-300 bg-white px-2.5 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50"
      >
        Expand all
      </button>
      <button
        type="button"
        onClick={onCollapseAll}
        className="rounded-md border border-slate-300 bg-white px-2.5 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50"
      >
        Collapse all
      </button>
      {matchCount !== null && (
        <span className="text-xs text-slate-500">
          {matchCount.toLocaleString()} match{matchCount === 1 ? "" : "es"}
        </span>
      )}
    </div>
  );
}

/** The virtualized, scrollable tree panel (header bar + windowed rows). */
function TreePanel({
  flat,
  headerColor,
  expanded,
  needle,
  selectedId,
  onToggle,
  onSelect,
  colorFor,
  query,
}: {
  flat: FlatRow[];
  headerColor: CbsLevelColor;
  expanded: Set<number>;
  needle: string;
  selectedId: number | null;
  onToggle: (id: number) => void;
  onSelect: (node: CbsNode) => void;
  colorFor: ColorFn;
  query: string;
}) {
  // Virtualize so only the rows in view are in the DOM — "Expand all" over
  // thousands of nodes stays cheap, and scroll/select/toggle never re-render
  // the whole tree.
  const scrollRef = React.useRef<HTMLDivElement | null>(null);
  const rowVirtualizer = useVirtualizer({
    count: flat.length,
    getScrollElement: () => scrollRef.current,
    estimateSize: () => 29,
    overscan: 12,
  });

  return (
    <div className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm">
      <div
        className="flex items-center gap-2 px-3 py-2 text-xs font-semibold"
        style={{ backgroundColor: headerColor.fill, color: headerColor.text }}
      >
        CBS code &amp; name
        <span className="ml-auto opacity-80">UOM</span>
      </div>
      {flat.length === 0 ? (
        <p className="p-6 text-center text-sm text-slate-500">
          No rows match “{query}”.
        </p>
      ) : (
        <div
          ref={scrollRef}
          role="tree"
          aria-label="CBS hierarchy"
          className="max-h-[70vh] overflow-auto"
        >
          <div
            style={{ height: rowVirtualizer.getTotalSize(), position: "relative" }}
          >
            {rowVirtualizer.getVirtualItems().map((vi) => {
              const { node, depth } = flat[vi.index];
              return (
                <div
                  key={node.id}
                  data-index={vi.index}
                  ref={rowVirtualizer.measureElement}
                  style={{
                    position: "absolute",
                    top: 0,
                    left: 0,
                    width: "100%",
                    transform: `translateY(${vi.start}px)`,
                  }}
                >
                  <CbsRow
                    node={node}
                    depth={depth}
                    hasChildren={node.children.length > 0}
                    isOpen={needle.length > 0 || expanded.has(node.id)}
                    isSelected={selectedId === node.id}
                    onToggle={onToggle}
                    onSelect={onSelect}
                    color={colorFor(node.level)}
                  />
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}

/** The provenance/rebuild footer line. */
function SourceFooter({ meta }: { meta: CbsData["meta"] }) {
  return (
    <p className="mt-2 text-[11px] text-slate-400">
      Source: {meta.source} ({meta.sheetName}) · generated{" "}
      {new Date(meta.generatedAt).toLocaleDateString()}. Colours and outline
      mirror the workbook; rebuild with{" "}
      <code className="rounded bg-slate-100 px-1">
        tsx scripts/build-cbs-sample.ts
      </code>{" "}
      after CBS changes.
    </p>
  );
}

/** The collapsible tree + toolbar + detail for one CBS dataset. Owns the state
 *  and derivation; the presentational pieces above take plain props. */
function CbsHierarchy({ data }: { data: CbsData }) {
  const { meta } = data;
  const colorFor = React.useCallback<ColorFn>(
    (level) =>
      level === 0
        ? L0_COLOR
        : (meta.levelColors[String(level)] ?? DEFAULT_LEVEL_COLOR),
    [meta.levelColors],
  );

  const [expanded, setExpanded] = React.useState<Set<number>>(() => new Set());
  const [selected, setSelected] = React.useState<CbsNode | null>(null);
  const [query, setQuery] = React.useState("");

  const needle = query.trim().toLowerCase();
  const { nodes, matches } = React.useMemo(
    () => (needle ? filterTree(data.nodes, needle) : { nodes: data.nodes, matches: 0 }),
    [needle, data.nodes],
  );

  const toggle = React.useCallback((id: number) => {
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }, []);

  const allIdsWithChildren = React.useMemo(() => {
    const ids: number[] = [];
    const rec = (list: CbsNode[]) => {
      for (const n of list) {
        if (n.children.length > 0) ids.push(n.id);
        rec(n.children);
      }
    };
    rec(data.nodes);
    return ids;
  }, [data.nodes]);

  const flat = React.useMemo(
    () => flattenVisible(nodes, expanded, needle.length > 0),
    [nodes, expanded, needle],
  );

  const levels = Object.keys(meta.levelColors)
    .map(Number)
    .sort((a, b) => a - b);

  return (
    <div className="px-4 pb-4 md:px-5">
      {meta.subtitle && (
        <p className="mt-1 mb-3 max-w-3xl text-sm text-slate-500">
          {meta.subtitle}
        </p>
      )}

      <CountsLegend counts={meta.counts} levels={levels} colorFor={colorFor} />
      <HierarchyToolbar
        query={query}
        setQuery={setQuery}
        onExpandAll={() => setExpanded(new Set(allIdsWithChildren))}
        onCollapseAll={() => setExpanded(new Set())}
        matchCount={needle ? matches : null}
      />

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-[1fr_22rem]">
        <TreePanel
          flat={flat}
          headerColor={meta.headerColor}
          expanded={expanded}
          needle={needle}
          selectedId={selected?.id ?? null}
          onToggle={toggle}
          onSelect={setSelected}
          colorFor={colorFor}
          query={query}
        />

        <aside className="hidden rounded-lg border border-slate-200 bg-white shadow-sm lg:block lg:self-start">
          {selected ? (
            <DetailPanel
              node={selected}
              detailColumns={meta.detailColumns}
              color={colorFor(selected.level)}
              onClose={() => setSelected(null)}
            />
          ) : (
            <p className="p-6 text-sm text-slate-500">
              Select a row to see its full CBS detail (UOM, cost code, account,
              discipline, description, and more).
            </p>
          )}
        </aside>
      </div>

      <SourceFooter meta={meta} />
    </div>
  );
}

/** A collapsible section whose (large) dataset is imported the first time it opens. */
function CbsSection({
  title,
  description,
  load,
  defaultOpen = false,
}: {
  title: string;
  description: string;
  load: () => Promise<CbsData>;
  defaultOpen?: boolean;
}) {
  const [open, setOpen] = React.useState(defaultOpen);
  const [data, setData] = React.useState<CbsData | null>(null);
  // One-shot guard: fetch the dataset the first time the section opens. A ref
  // (not a `loading` state in the deps) so re-renders during the fetch don't
  // re-trigger or cancel it.
  const startedRef = React.useRef(false);

  React.useEffect(() => {
    if (!open || data || startedRef.current) return;
    startedRef.current = true;
    load().then(setData);
  }, [open, data, load]);

  return (
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        aria-expanded={open}
        className="flex w-full items-center gap-3 px-4 py-3 text-left hover:bg-slate-50"
      >
        <ChevronRight
          size={18}
          className={`shrink-0 text-slate-400 transition-transform ${open ? "rotate-90" : ""}`}
        />
        <div className="min-w-0">
          <h2 className="text-base font-bold text-slate-800">{title}</h2>
          <p className="truncate text-xs text-slate-500">{description}</p>
        </div>
        {data && (
          <span className="ml-auto shrink-0 rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-600">
            {data.meta.counts.total.toLocaleString()} rows
          </span>
        )}
      </button>
      {open && (
        <div className="border-t border-slate-100">
          {data ? (
            <CbsHierarchy data={data} />
          ) : (
            <div className="flex items-center gap-2 px-4 py-10 text-sm text-slate-500">
              <Loader2 size={16} className="animate-spin" /> Loading CBS data…
            </div>
          )}
        </div>
      )}
    </section>
  );
}

// Module-level (stable) loaders — each dataset is its own lazily-fetched chunk.
// Relative paths (not the `~` alias) so the dynamic import resolves under both
// the Vite build and the vitest runner.
const loadCodeBook = (): Promise<CbsData> =>
  import("../../config/cbs-codebook").then((m) => m.cbsCodeBook);
const loadDictionary = (): Promise<CbsData> =>
  import("../../config/cbs-sample").then((m) => m.cbsSample);

export function CbsSampleView() {
  return (
    <div className="mx-auto max-w-7xl px-4 py-6 md:px-8">
      <header className="mb-4">
        <h1 className="text-2xl font-bold text-slate-800">CBS Sample</h1>
        <p className="mt-1 max-w-3xl text-sm text-slate-500">
          The cost breakdown structure laid out as a colour-coded, collapsible
          hierarchy — colours and grouping mirror the source workbooks.
        </p>
      </header>

      <div className="flex flex-col gap-4">
        <CbsSection
          title="CBS Code Book"
          description="Civil, Equipment, Pipe Shop & Coatings — original rows only (no generated S/M)."
          load={loadCodeBook}
          defaultOpen
        />
        <CbsSection
          title="Master CBS Dictionary"
          description="Civil, Shop Equipment, Equipment, Pipe Shop & Piping — with generated S/M rows."
          load={loadDictionary}
          defaultOpen
        />
      </div>
    </div>
  );
}
