import * as React from "react";
import { ChevronRight, Search, X } from "lucide-react";
import { cbsSample as cbs } from "~/config/cbs-sample";
import type { CbsLevelColor, CbsNode } from "~/config/cbs-sample-types";

/**
 * Web view of the formatted CBS sample workbook (prisma/data/SampleCSB.xlsx).
 * The data + per-level colours are generated by scripts/build-cbs-sample.ts;
 * this renders them as a collapsible hierarchy that mirrors the workbook's own
 * outline grouping and colour-by-depth scheme.
 */

const colorFor = (level: number): CbsLevelColor =>
  cbs.meta.levelColors[String(level)] ?? { fill: "#ffffff", text: "#000000" };

/** Role suffix a row carries, if any — the workbook's generated Sub/Material rows. */
function rowTypeBadge(rowType: string): { label: string; title: string } | null {
  if (rowType.includes("Sub")) return { label: "S", title: "Sub-code row" };
  if (rowType.includes("Material")) return { label: "M", title: "Material row" };
  return null;
}

/** Keep only nodes matching `q` (by name or code) plus their ancestors. */
function filterTree(
  nodes: CbsNode[],
  needle: string,
): { nodes: CbsNode[]; matches: number } {
  let matches = 0;
  const rec = (list: CbsNode[]): CbsNode[] => {
    const out: CbsNode[] = [];
    for (const n of list) {
      const selfMatch =
        n.name.toLowerCase().includes(needle) ||
        n.code.toLowerCase().includes(needle);
      const kids = rec(n.children);
      if (selfMatch || kids.length > 0) {
        if (selfMatch) matches++;
        out.push({ ...n, children: kids });
      }
    }
    return out;
  };
  return { nodes: rec(nodes), matches };
}

function CbsRow({
  node,
  depth,
  expanded,
  onToggle,
  selectedId,
  onSelect,
  forceExpand,
}: {
  node: CbsNode;
  depth: number;
  expanded: Set<number>;
  onToggle: (id: number) => void;
  selectedId: number | null;
  onSelect: (node: CbsNode) => void;
  forceExpand: boolean;
}) {
  const hasChildren = node.children.length > 0;
  const isOpen = forceExpand || expanded.has(node.id);
  const color = colorFor(node.level);
  const badge = rowTypeBadge(node.rowType);
  const uom = node.fields["UOM"];
  const selected = selectedId === node.id;

  return (
    <>
      <div
        role="treeitem"
        aria-level={node.level + 1}
        aria-expanded={hasChildren ? isOpen : undefined}
        aria-selected={selected}
        onClick={() => onSelect(node)}
        style={{
          backgroundColor: color.fill,
          color: color.text,
          paddingLeft: 8 + depth * 18,
        }}
        className={`flex cursor-pointer items-center gap-2 border-b border-black/5 py-1 pr-3 text-sm transition-[filter] hover:brightness-95 ${
          selected ? "ring-2 ring-inset ring-sky-900/60" : ""
        }`}
      >
        {hasChildren ? (
          <button
            type="button"
            aria-label={isOpen ? "Collapse" : "Expand"}
            onClick={(e) => {
              e.stopPropagation();
              onToggle(node.id);
            }}
            className="grid size-4 shrink-0 place-items-center rounded hover:bg-black/10"
          >
            <ChevronRight
              size={13}
              className={`transition-transform ${isOpen ? "rotate-90" : ""}`}
            />
          </button>
        ) : (
          <span className="size-4 shrink-0 text-center opacity-40">·</span>
        )}
        <span className="shrink-0 font-mono text-xs tabular-nums opacity-80">
          {node.code}
        </span>
        <span className="truncate font-medium">{node.name}</span>
        {badge && (
          <span
            title={badge.title}
            className="shrink-0 rounded border border-current/30 px-1 text-[10px] leading-4 font-semibold opacity-70"
          >
            {badge.label}
          </span>
        )}
        {uom && (
          <span className="ml-auto shrink-0 font-mono text-[11px] opacity-70">
            {uom}
          </span>
        )}
      </div>
      {hasChildren &&
        isOpen &&
        node.children.map((child) => (
          <CbsRow
            key={child.id}
            node={child}
            depth={depth + 1}
            expanded={expanded}
            onToggle={onToggle}
            selectedId={selectedId}
            onSelect={onSelect}
            forceExpand={forceExpand}
          />
        ))}
    </>
  );
}

function DetailPanel({
  node,
  onClose,
}: {
  node: CbsNode;
  onClose: () => void;
}) {
  const color = colorFor(node.level);
  return (
    <div className="flex h-full flex-col">
      <div
        className="flex items-start justify-between gap-2 rounded-t-lg px-4 py-3"
        style={{ backgroundColor: color.fill, color: color.text }}
      >
        <div className="min-w-0">
          <div className="font-mono text-xs tabular-nums opacity-80">
            {node.code}
          </div>
          <div className="text-sm font-semibold break-words">{node.name}</div>
          <div className="mt-0.5 text-[11px] opacity-70">
            Level {node.level} · {node.rowType}
          </div>
        </div>
        <button
          type="button"
          onClick={onClose}
          aria-label="Close details"
          className="shrink-0 rounded p-0.5 hover:bg-black/10"
        >
          <X size={15} />
        </button>
      </div>
      <dl className="min-h-0 flex-1 divide-y divide-slate-100 overflow-y-auto px-4 py-2 text-sm">
        {cbs.meta.detailColumns
          .filter((col) => node.fields[col])
          .map((col) => (
            <div key={col} className="grid grid-cols-[9rem_1fr] gap-2 py-1.5">
              <dt className="text-xs font-medium text-slate-500">{col}</dt>
              <dd className="break-words text-slate-800">{node.fields[col]}</dd>
            </div>
          ))}
      </dl>
    </div>
  );
}

export function CbsSampleView() {
  const [expanded, setExpanded] = React.useState<Set<number>>(
    // Start with the top-level disciplines expanded.
    () => new Set(cbs.nodes.map((n) => n.id)),
  );
  const [selected, setSelected] = React.useState<CbsNode | null>(null);
  const [query, setQuery] = React.useState("");

  const needle = query.trim().toLowerCase();
  const { nodes, matches } = React.useMemo(
    () => (needle ? filterTree(cbs.nodes, needle) : { nodes: cbs.nodes, matches: 0 }),
    [needle],
  );

  const toggle = React.useCallback((id: number) => {
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }, []);

  const allIdsWithChildren = React.useMemo(() => {
    const ids: number[] = [];
    const rec = (list: CbsNode[]) => {
      for (const n of list) {
        if (n.children.length > 0) ids.push(n.id);
        rec(n.children);
      }
    };
    rec(cbs.nodes);
    return ids;
  }, []);

  const { counts, levelColors } = cbs.meta;
  const levels = Object.keys(levelColors)
    .map(Number)
    .sort((a, b) => a - b);

  return (
    <div className="mx-auto flex h-full max-w-7xl flex-col px-4 py-6 md:px-8">
      <header className="mb-4 shrink-0">
        <h1 className="text-2xl font-bold text-slate-800">CBS Sample</h1>
        <p className="mt-1 max-w-3xl text-sm text-slate-500">{cbs.meta.subtitle}</p>
        <div className="mt-3 flex flex-wrap items-center gap-2 text-xs">
          <span className="rounded-full bg-slate-100 px-2.5 py-1 font-medium text-slate-700">
            {counts.total.toLocaleString()} rows
          </span>
          <span className="rounded-full bg-slate-100 px-2.5 py-1 text-slate-600">
            {counts.original.toLocaleString()} original
          </span>
          <span className="rounded-full bg-slate-100 px-2.5 py-1 text-slate-600">
            {counts.subRows} sub · {counts.materialRows} material
          </span>
          {/* Level colour legend — the workbook's own colour-by-depth key. */}
          <span className="ml-1 flex flex-wrap items-center gap-1">
            {levels.map((lvl) => (
              <span
                key={lvl}
                title={`Level ${lvl}`}
                className="rounded px-1.5 py-0.5 text-[10px] font-semibold"
                style={{
                  backgroundColor: levelColors[String(lvl)].fill,
                  color: levelColors[String(lvl)].text,
                  outline: "1px solid rgba(0,0,0,0.1)",
                }}
              >
                L{lvl}
              </span>
            ))}
          </span>
        </div>
      </header>

      <div className="mb-3 flex flex-wrap items-center gap-2 shrink-0">
        <div className="relative">
          <Search
            size={14}
            className="absolute top-1/2 left-2 -translate-y-1/2 text-slate-400"
          />
          <input
            type="search"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search code or name…"
            aria-label="Search the CBS sample"
            className="h-8 w-64 rounded-md border border-slate-200 bg-white pr-2 pl-7 text-sm text-slate-700 outline-none placeholder:text-slate-400 focus-visible:border-slate-400"
          />
        </div>
        <button
          type="button"
          onClick={() => setExpanded(new Set(allIdsWithChildren))}
          className="rounded-md border border-slate-300 bg-white px-2.5 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50"
        >
          Expand all
        </button>
        <button
          type="button"
          onClick={() => setExpanded(new Set())}
          className="rounded-md border border-slate-300 bg-white px-2.5 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50"
        >
          Collapse all
        </button>
        {needle && (
          <span className="text-xs text-slate-500">
            {matches.toLocaleString()} match{matches === 1 ? "" : "es"}
          </span>
        )}
      </div>

      <div className="grid min-h-0 flex-1 grid-cols-1 gap-4 lg:grid-cols-[1fr_22rem]">
        <div className="min-h-0 overflow-auto rounded-lg border border-slate-200 bg-white shadow-sm">
          <div
            className="sticky top-0 z-10 flex items-center gap-2 px-3 py-2 text-xs font-semibold"
            style={{
              backgroundColor: cbs.meta.headerColor.fill,
              color: cbs.meta.headerColor.text,
            }}
          >
            CBS code &amp; name
            <span className="ml-auto opacity-80">UOM</span>
          </div>
          <div role="tree" aria-label="CBS hierarchy">
            {nodes.length === 0 ? (
              <p className="p-6 text-center text-sm text-slate-500">
                No rows match “{query}”.
              </p>
            ) : (
              nodes.map((node) => (
                <CbsRow
                  key={node.id}
                  node={node}
                  depth={0}
                  expanded={expanded}
                  onToggle={toggle}
                  selectedId={selected?.id ?? null}
                  onSelect={setSelected}
                  forceExpand={needle.length > 0}
                />
              ))
            )}
          </div>
        </div>

        <aside className="hidden min-h-0 rounded-lg border border-slate-200 bg-white shadow-sm lg:block">
          {selected ? (
            <DetailPanel node={selected} onClose={() => setSelected(null)} />
          ) : (
            <p className="p-6 text-sm text-slate-500">
              Select a row to see its full CBS detail (UOM, cost code, account,
              discipline, description, and more).
            </p>
          )}
        </aside>
      </div>

      <p className="mt-2 shrink-0 text-[11px] text-slate-400">
        Source: {cbs.meta.source} · generated{" "}
        {new Date(cbs.meta.generatedAt).toLocaleDateString()}. Colours and
        outline mirror the workbook; rebuild with{" "}
        <code className="rounded bg-slate-100 px-1">
          tsx scripts/build-cbs-sample.ts
        </code>{" "}
        after CBS changes.
      </p>
    </div>
  );
}
