/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as PipingRouteImport } from './routes/piping'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as FcoLogRouteImport } from './routes/fco-log'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BasisRouteImport } from './routes/basis'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DisciplineRouteImport } from './routes/$discipline'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubcontractorsRouteImport } from './routes/admin.subcontractors'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminAreasRouteImport } from './routes/admin.areas'

const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PipingRoute = PipingRouteImport.update({
  id: '/piping',
  path: '/piping',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const FcoLogRoute = FcoLogRouteImport.update({
  id: '/fco-log',
  path: '/fco-log',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BasisRoute = BasisRouteImport.update({
  id: '/basis',
  path: '/basis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplineRoute = DisciplineRouteImport.update({
  id: '/$discipline',
  path: '/$discipline',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubcontractorsRoute = AdminSubcontractorsRouteImport.update({
  id: '/subcontractors',
  path: '/subcontractors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAreasRoute = AdminAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$discipline': typeof DisciplineRoute
  '/admin': typeof AdminRouteWithChildren
  '/basis': typeof BasisRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/fco-log': typeof FcoLogRoute
  '/materials': typeof MaterialsRoute
  '/piping': typeof PipingRoute
  '/setup': typeof SetupRoute
  '/summary': typeof SummaryRoute
  '/validation': typeof ValidationRoute
  '/admin/areas': typeof AdminAreasRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/subcontractors': typeof AdminSubcontractorsRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$discipline': typeof DisciplineRoute
  '/admin': typeof AdminRouteWithChildren
  '/basis': typeof BasisRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/fco-log': typeof FcoLogRoute
  '/materials': typeof MaterialsRoute
  '/piping': typeof PipingRoute
  '/setup': typeof SetupRoute
  '/summary': typeof SummaryRoute
  '/validation': typeof ValidationRoute
  '/admin/areas': typeof AdminAreasRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/subcontractors': typeof AdminSubcontractorsRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$discipline': typeof DisciplineRoute
  '/admin': typeof AdminRouteWithChildren
  '/basis': typeof BasisRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/fco-log': typeof FcoLogRoute
  '/materials': typeof MaterialsRoute
  '/piping': typeof PipingRoute
  '/setup': typeof SetupRoute
  '/summary': typeof SummaryRoute
  '/validation': typeof ValidationRoute
  '/admin/areas': typeof AdminAreasRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/subcontractors': typeof AdminSubcontractorsRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$discipline'
    | '/admin'
    | '/basis'
    | '/changelog'
    | '/dashboard'
    | '/fco-log'
    | '/materials'
    | '/piping'
    | '/setup'
    | '/summary'
    | '/validation'
    | '/admin/areas'
    | '/admin/projects'
    | '/admin/subcontractors'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$discipline'
    | '/admin'
    | '/basis'
    | '/changelog'
    | '/dashboard'
    | '/fco-log'
    | '/materials'
    | '/piping'
    | '/setup'
    | '/summary'
    | '/validation'
    | '/admin/areas'
    | '/admin/projects'
    | '/admin/subcontractors'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/$discipline'
    | '/admin'
    | '/basis'
    | '/changelog'
    | '/dashboard'
    | '/fco-log'
    | '/materials'
    | '/piping'
    | '/setup'
    | '/summary'
    | '/validation'
    | '/admin/areas'
    | '/admin/projects'
    | '/admin/subcontractors'
    | '/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisciplineRoute: typeof DisciplineRoute
  AdminRoute: typeof AdminRouteWithChildren
  BasisRoute: typeof BasisRoute
  ChangelogRoute: typeof ChangelogRoute
  DashboardRoute: typeof DashboardRoute
  FcoLogRoute: typeof FcoLogRoute
  MaterialsRoute: typeof MaterialsRoute
  PipingRoute: typeof PipingRoute
  SetupRoute: typeof SetupRoute
  SummaryRoute: typeof SummaryRoute
  ValidationRoute: typeof ValidationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piping': {
      id: '/piping'
      path: '/piping'
      fullPath: '/piping'
      preLoaderRoute: typeof PipingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fco-log': {
      id: '/fco-log'
      path: '/fco-log'
      fullPath: '/fco-log'
      preLoaderRoute: typeof FcoLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basis': {
      id: '/basis'
      path: '/basis'
      fullPath: '/basis'
      preLoaderRoute: typeof BasisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$discipline': {
      id: '/$discipline'
      path: '/$discipline'
      fullPath: '/$discipline'
      preLoaderRoute: typeof DisciplineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subcontractors': {
      id: '/admin/subcontractors'
      path: '/subcontractors'
      fullPath: '/admin/subcontractors'
      preLoaderRoute: typeof AdminSubcontractorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/areas': {
      id: '/admin/areas'
      path: '/areas'
      fullPath: '/admin/areas'
      preLoaderRoute: typeof AdminAreasRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAreasRoute: typeof AdminAreasRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSubcontractorsRoute: typeof AdminSubcontractorsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAreasRoute: AdminAreasRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSubcontractorsRoute: AdminSubcontractorsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisciplineRoute: DisciplineRoute,
  AdminRoute: AdminRouteWithChildren,
  BasisRoute: BasisRoute,
  ChangelogRoute: ChangelogRoute,
  DashboardRoute: DashboardRoute,
  FcoLogRoute: FcoLogRoute,
  MaterialsRoute: MaterialsRoute,
  PipingRoute: PipingRoute,
  SetupRoute: SetupRoute,
  SummaryRoute: SummaryRoute,
  ValidationRoute: ValidationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
