/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as PipingRouteImport } from './routes/piping'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as ChangelogV2RouteImport } from './routes/changelog-v2'
import { Route as BasisRouteImport } from './routes/basis'
import { Route as DisciplineRouteImport } from './routes/$discipline'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiPostsRouteImport } from './routes/api/posts'
import { Route as ApiUsersIdRouteImport } from './routes/api/users.$id'

const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PipingRoute = PipingRouteImport.update({
  id: '/piping',
  path: '/piping',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogV2Route = ChangelogV2RouteImport.update({
  id: '/changelog-v2',
  path: '/changelog-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const BasisRoute = BasisRouteImport.update({
  id: '/basis',
  path: '/basis',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplineRoute = DisciplineRouteImport.update({
  id: '/$discipline',
  path: '/$discipline',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsRoute = ApiPostsRouteImport.update({
  id: '/api/posts',
  path: '/api/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$discipline': typeof DisciplineRoute
  '/basis': typeof BasisRoute
  '/changelog-v2': typeof ChangelogV2Route
  '/materials': typeof MaterialsRoute
  '/piping': typeof PipingRoute
  '/setup': typeof SetupRoute
  '/summary': typeof SummaryRoute
  '/validation': typeof ValidationRoute
  '/api/posts': typeof ApiPostsRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/api/users/$id': typeof ApiUsersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$discipline': typeof DisciplineRoute
  '/basis': typeof BasisRoute
  '/changelog-v2': typeof ChangelogV2Route
  '/materials': typeof MaterialsRoute
  '/piping': typeof PipingRoute
  '/setup': typeof SetupRoute
  '/summary': typeof SummaryRoute
  '/validation': typeof ValidationRoute
  '/api/posts': typeof ApiPostsRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/api/users/$id': typeof ApiUsersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$discipline': typeof DisciplineRoute
  '/basis': typeof BasisRoute
  '/changelog-v2': typeof ChangelogV2Route
  '/materials': typeof MaterialsRoute
  '/piping': typeof PipingRoute
  '/setup': typeof SetupRoute
  '/summary': typeof SummaryRoute
  '/validation': typeof ValidationRoute
  '/api/posts': typeof ApiPostsRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/api/users/$id': typeof ApiUsersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$discipline'
    | '/basis'
    | '/changelog-v2'
    | '/materials'
    | '/piping'
    | '/setup'
    | '/summary'
    | '/validation'
    | '/api/posts'
    | '/api/users'
    | '/api/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$discipline'
    | '/basis'
    | '/changelog-v2'
    | '/materials'
    | '/piping'
    | '/setup'
    | '/summary'
    | '/validation'
    | '/api/posts'
    | '/api/users'
    | '/api/users/$id'
  id:
    | '__root__'
    | '/'
    | '/$discipline'
    | '/basis'
    | '/changelog-v2'
    | '/materials'
    | '/piping'
    | '/setup'
    | '/summary'
    | '/validation'
    | '/api/posts'
    | '/api/users'
    | '/api/users/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisciplineRoute: typeof DisciplineRoute
  BasisRoute: typeof BasisRoute
  ChangelogV2Route: typeof ChangelogV2Route
  MaterialsRoute: typeof MaterialsRoute
  PipingRoute: typeof PipingRoute
  SetupRoute: typeof SetupRoute
  SummaryRoute: typeof SummaryRoute
  ValidationRoute: typeof ValidationRoute
  ApiPostsRoute: typeof ApiPostsRoute
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piping': {
      id: '/piping'
      path: '/piping'
      fullPath: '/piping'
      preLoaderRoute: typeof PipingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog-v2': {
      id: '/changelog-v2'
      path: '/changelog-v2'
      fullPath: '/changelog-v2'
      preLoaderRoute: typeof ChangelogV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basis': {
      id: '/basis'
      path: '/basis'
      fullPath: '/basis'
      preLoaderRoute: typeof BasisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$discipline': {
      id: '/$discipline'
      path: '/$discipline'
      fullPath: '/$discipline'
      preLoaderRoute: typeof DisciplineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts': {
      id: '/api/posts'
      path: '/api/posts'
      fullPath: '/api/posts'
      preLoaderRoute: typeof ApiPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
  }
}

interface ApiUsersRouteChildren {
  ApiUsersIdRoute: typeof ApiUsersIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersIdRoute: ApiUsersIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisciplineRoute: DisciplineRoute,
  BasisRoute: BasisRoute,
  ChangelogV2Route: ChangelogV2Route,
  MaterialsRoute: MaterialsRoute,
  PipingRoute: PipingRoute,
  SetupRoute: SetupRoute,
  SummaryRoute: SummaryRoute,
  ValidationRoute: ValidationRoute,
  ApiPostsRoute: ApiPostsRoute,
  ApiUsersRoute: ApiUsersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
